### ISSUE TITLE
Set OOC Metainfo verb does not change metainfo

### ISSUE THREAD

**Issue by CRTXBacon** [CHOMPStation2/CHOMPStation2#1119]
#### Brief description of the issue
Set-OOC-Metainfo verb does not change metainfo.

#### What you expected to happen
The verb to change metainfo.

#### What actually happened
The verb opens the text input to change metainfo but the change never takes effect.

#### Steps to reproduce
- Use the Set-OOC-Metainfo verb
- Read your OOC notes
- Notice the lack of change

#### Code Revision
Commit 914e83b6a56f2be65ef42c19eeec4509bba7f7d6

**Comment by Razgriz1032** [comment]
1. Have you tried clicking save.
2. Have you tried leaving the round and rejoining.
3. Have you tried waiting for new round.

Because when I modify my OOC notes through character creator after I have spawned, the changes don't take effect until after the round is over afaik, because I myself haven't tried #2 and I frankly don't want to try because effort and it's something that doesn't actually seem to be broken.


Also is that even a verb?
![image](https://user-images.githubusercontent.com/15962836/104399094-3958f880-550d-11eb-9bc0-af31e9a47fd0.png)

**Comment by Razgriz1032** [comment]
I suspect all you gotta do is number 2 because the shit's loaded in when you join the round. I'm assuming it's not gonna keep refreshing your OOC notes every tick because that's just inefficient.

**Comment by CRTXBacon** [comment]
As I said, this is with the VERB (as in during a round), not the setting in the character creator.

**Comment by CRTXBacon** [comment]
![image](https://user-images.githubusercontent.com/34610106/104399954-a1c5cb00-5549-11eb-8bc1-d6b5f07ceb0b.png)
And yes it's a verb

**Comment by Razgriz1032** [comment]
Ok, yeah it's broken.

As an alternative, you might be able to edit it with this other verb, but it won't take effect until you leave and spawn back in, unfortunately.

![image](https://user-images.githubusercontent.com/15962836/104402133-e08c5e80-5512-11eb-83cc-27c5d0feea08.png)

**Comment by radiantAurora** [comment]
Different account but original issue poster, tested today and this appears to be fixed now.
