### ISSUE TITLE
should be able to pull down the black face masks

### ISSUE THREAD

**Issue by kcin2001** [CHOMPStation2/CHOMPStation2#1181]
#### Brief overview of the feature
just like the normal breath masks you should be able to pull down the black face masks for easy eating/drinking without having to unequip it completely

**Comment by CommodoreYouth** [comment]
I believe that's the tradeoff with the Breath Mask vs Face Mask.  One is just for internals use, and is quick and easy to put on or move around.  The other is a full on lower-face covering protective mask, and is more difficult to move or remove.

On the one hand, the Breath Mask is just an airtight rubber mask with elastic cloth straps to hold it against your mouth and nose.
Of course you can pull it down with ease, or eat and drink with it one because of how easy it is to pull down.

The Face Mask on the other hand, is a full on lower-face covering rubber/kevlar mask with straps that needs to be tightened with a buckle around the back of your head, or a clasping buckle.

Look at the following examples and determine which one would be easier to just pull down for a moment to say, pop a pill, take a sip of something, or bite into a snack.
![70ef395cee2ea9c61a5db9dbb15f4f31346be645_original](https://user-images.githubusercontent.com/11749157/106520360-acb9ae80-64aa-11eb-8847-4de68537387c.jpeg)
![B2278858](https://user-images.githubusercontent.com/11749157/106520366-adeadb80-64aa-11eb-9455-4b643d7afcc8.jpg)
