### ISSUE TITLE
Proteans Stunlocked Forever when Radiation/Toxin stunned

### ISSUE THREAD

**Issue by icowom** [CHOMPStation2/CHOMPStation2#1749]
#### Brief description of the issue
Proteans have a gamebreaking bug where if you have radiation/toxin damage, and you switch to a the Protean goo form to try and heal the actual damage. You'll get stunlocked. Unable to shift back because the game says you need more nanites. Even when you're full of it. Whole exploration team tried to fix this, couldn't work, couldn't even even be logged out. Hours later and the stun still hasn't worn out

#### What you expected to happen
Be able to shift back to humanoid form even when afflicted, or to have the stun period actually have breaks to allow shifting back

#### What actually happened
Permanently stunned, unable to use any abilities to shift back.

#### Steps to reproduce
- (Step 1) Get radiation/toxins damage while in humanoid form.
- (Step 2) Take damage from the lingering radiation and try to repair by becoming Protean Goo
- (Step3) Get stunlocked forever

**Comment by Razgriz1032** [comment]
Current problem:
Proteans can take radiation and toxin damage and will take away health, but the nanites are unable to heal that type of damage.

Possible solution:
Convert radiation and toxin damage to burn damage. Add a cap to the maximum damage taken per tick from radiation, but severe enough so that they can't spend a long time around the engine or a rad storm.

I am not sure how to code damage conversion.
