### ISSUE TITLE
Resleeving UPDATED

### ISSUE THREAD

**Issue by Vulpias** [CHOMPStation2/CHOMPStation2#188]
#### Brief overview of the feature
Change the way you are resleeved. Adding new features to it. 

#### What you want to happen
You can choose between two types of resleeving. 
With a Bio Brain, ( A biological brain) 
or a cyberbrain ( a brain that works like a big nif, being brain and nif in one, taking no brain dmg via any poison, or lack of air, but is damageable via electro dmg)

Choosing between those two would result in different resleeving and mind upload times. 
Copy + Paste a image on a cyberbrain would take nano seconds

meanwhile the upload on a biobrain would take longer, (up to a minute) 
to make resleeving something that takes time and isnt instant, adding game mechanics to the brains so they can be used for events.

**Comment by ExabyteDiscord** [comment]
I'm not sure how necessary this would be. Wouldn't this effectively just be robotics' job? The sleever can't even print synthetic body parts by design. If you're looking for a way to have a synthetic brain in a human body, perhaps it'd be better to make that a thing rather than modifying the sleever.

You do bring up a point though with the sleever being fast, I don't have a clue as to why it was made to go hyperspeed but it still does.

**Comment by Vulpias** [comment]
idea is that you can customize your body, and decide to be sleeved with synth parts implanted, and not fully bio.

**Comment by Darlantanis** [comment]
How is this any different than organic versus synthetic resleeving? Most of the features you describe sound like a synth. It's also already possible to resleeve organics with synthetic organs.

**Comment by Darlantanis** [comment]
This basically already exists via synthetic characters and synth resleeving while the actual mind-addition part of resleeving already takes seconds to accomplish. As for making carbons immune to toxin/oxy with a different brain type, no. That's a massive change to damage balancing and would quickly become meta due to plenty of existing content becoming obsolete just from an internal organ change. You'd also need to code in a new damage type. Unless by electro damage you mean energy weapons but considering the purpose of energy weapons is non-lethal take-down that's not feasible either as it removes security's main non-lethal ranged method of incapacitating crew.
