### ISSUE TITLE
Belt Miner Bugs/Issues

### ISSUE THREAD

**Issue by TheFurryFeline** [CHOMPStation2/CHOMPStation2#193]
Mostly a reminder for @Rykka-Stormheart to deal with.

Smol quips:

- Belter Outpost

- - Outpost power seems to bleed out a fair bit quickly.

- - Wiring from solars to the airlock to have space plating instead 

- - Runtimes when shuttle leaves the transition area as shown in https://discordapp.com/channels/180538463655821312/405257702663782400/669761697845608450

- - Maybe a suit cycler room as well as two extra voidsuits as reserve.

- - _Lessen the power draw from atmospherics in the main room_

- - 1 light switch per area is _fine_

- - Not enough solar panels to give power to the whole outpost.

- POI issues.

- - Crates POI are empty crates, treasure/reward thingy not set, as said in deadchat.

- - Frost spider POI has regular frost spooders and space variations spawning at once.

- - Another spooder POI https://discordapp.com/channels/180538463655821312/405257702663782400/669753224760131590, intended per discord chatter to change into carp spawns, I believe.

- - Mobs in other areas seem to be dying: bats, hounds, bears, space variation of frost spooders.

- - Faction issues with mobs spawned inside a POI being at odds with each other. https://cdn.discordapp.com/attachments/405257702663782400/670325354287595530/unknown.png for refference.

#### Code Revision
- Server revision: master - 2020-01-23
a0b222307faf01b029bf5567cb33b061ce8607ec 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Darlantanis** [comment]
Alright, here's my big list just from brief observations in dream-maker and a test server.

Planet-side
-The planet area for the shuttle lacks power and atmos connections
-No windows in the planet shuttle area
-The "rshull" walls for the belter shuttle do not fit thematically with the other shuttles on our map. The same goes with the docking airlocks, every other docking area on the map uses red EVA airlocks.

Outpost
-Belt-miner solars are not on by roundstart, SMES should probably start with charge.
-Solar wires goes through a wall.
-The airlocks where the shuttle docks are not bolted at roundstart.
-There's no need for an RCON bypass on the outpost. The main purpose of this is dividing a grid into subgrids with lower power output and thus less danger when hitting wires. There is only one power grid here.
-The belter outpost itself seems to play ambiance in an endless loop. 
-Why does an outside area have an APC? Ideally lights here should not require power similar to Northern Star mining.
-Space in the center doesn't really fit here. If the outpost is embedded in (and surrounded by) an asteroid, why is the floor on top of space turfs? This seems to apply to the entire outpost, even the tunnel through rock where the solars wire is placed.
-The railings are backward at solars are backward.
-The emergency shutters dividing the gas canister storage room are silly. They also mean it's impossible to resolve atmos issues remotely because the scrubber is on the left side of the room.
-Typically you use plasteel walls to separate station from space. It would also fit the rest of the map for the outer walls to made of plasteel, this is true of the planet-side outposts which actually have a breathable atmosphere on the outside.
-Multiple instances of vents/scrubbers under tables in the dorms/first-aid area.
-The shelter pod sleeper is out-of-place with ever other sleeper on the map.
-The map of this z-level (check the minimap in dream-maker) looks like giant stone legos rather than asteroids (i.e. they look like giant rectangles instead of asteroids).
-Solars do not aesthetically fit our map. Solars set out in space should not be built on a platform but should instead be freely hanging in space on top of solar floors, refer to Northern Cross solar arrays and/or the Exploration Carrier solar arrays for reference (sidenote, this is because realistically you don't want a floor in the way when your solars can the sun below. I'm aware this isn't necessarily reflective of in-game mechanics). A platform like the current map is acceptable if the solars are in the asteroid instead of jutting into space (refer to outpost solars on Northern Cross or third floor solars on Southern Cross station). 
-I'm not sure I see any change in ore generation though this is difficult to quantify. Part of the point of a belt miner area is a higher risk, higher reward area than station mining. 
-No security cameras.
-The windows do no use proper plating beneath them.
-The dorms/first-aid/hallway air alarms do not seem to deploy shutters. Tested by deleting windows/walls to vent the rooms.
-How much equipment will be brought through the EVA airlocks? The area seems pretty big for a room that pumps down to vacuum/back to normal pressure.
-Many "misc" objects seem to be missing. Extinguishers, AI holopads, newscasters, status displays, AI status displays, etc. 
-If you want to keep the space windows in the dorms, you may consider electrochromatic ones.
-Disposals? Vending machines?

POI Issues
-The "no POI's allowed" area around the outpost needs to be bigger. On my test server a spider nest spawned 2 tiles away from solars. There was a spider horde (and robot) trying to break into the dorms within 5 minutes of the round starting. Removing the huge window walls from the dorms could also resolve this problem.
-POI generation is... off. I've seen many instances of POI's generating as squares floating in space instead of in the asteroids. 

Big Picture Edits
-Ideally the belter shuttle should be part of the station. One of the major complaints behind the request for asteroid mining was players needing wait on the planet-station shuttles to go the the mines then back to station.
-Adding to the above point, the outpost needs ore processing if the shuttle is moved to the station. This should come with a mining points vendor.
-The long, wrap-around pathway for the solars wire really makes me question the solars-SMES room placement. Wouldn't it make more sense to place the solars-SMES left of the gas canister storage with a short path to the solars and a second set of EVA airlocks?
-Consider mob spawns similar to Northern Star mines. There's room for more dangerous spawns since planet-side exists as a relatively safe alternative (although keep in mind AI changes might mean the mobs we had before are much more dangerous). Placing a belt-miner crate somewhere in the outpost might be wise if you do this. 

This is what I've noticed after about 30 minutes of poking around. It's possible there are other fixes needed.

**Comment by Darlantanis** [comment]
Oh, one other thing I spotted about belt mine atmos when closing dreammaker (so did not test to confirm in-game):
-I don't see any pumps or limiters on the air tank supplying the vents. Is the supply line at the same pressure as the air tank then? Be aware that higher supply line pressure means air vents will repressurize areas faster. If the pressure is high enough, vents will fill a room faster than a hole to space will empty it which (depending on air alarm placement) can vent your entire air supply to space. Which is problematic in an outpost with much more limited atmos.
-I also don't see any pumps on your scrubber line and assume siphoning air with scrubbers will be slowed as air builds up in the canister you're using for scrubber waste. Probably less of a problem given the small size of this outpost.
-There are no connections between your supply and scrubber lines meaning any siphoned gas will stay in waste; if for whatever reason all of the gas is siphoned away it will stay trapped in waste meaning the only fix is to re-add air manually. You can look at the atmos setups for the planet-side outposts and Exploration Carrier for an idea on how to get a breathable air mix back out of waste gas.

**Comment by Darlantanis** [comment]
Made irrelevant by #231
