### ISSUE TITLE
Regulators blocking air flow

### ISSUE THREAD

**Issue by KharlisSergal** [CHOMPStation2/CHOMPStation2#232]
#### Brief overview of the feature
Pressure regulators with automatic shutoff valves are blocking airflow to breached sections.
Some are also installed in the wrong direction.

#### What you want to happen
Remove these entirely and replace them with regular pipes.

#### Anything else you may wish to add:
Areas that become breached during meteors such as medical or the docking wing will not re pressurize until these are removed and replaced with regular pipes. They seem unnecessary as vents shut off automatically when they detect a steep drop in pressure.
![SS13](https://user-images.githubusercontent.com/61100501/74598135-dd0a0200-5039-11ea-8efd-4e29cf103a0a.jpg)

**Comment by Kazzc** [comment]
hrrmmfff... finding might be complicated, maybe. Lets see if I can get all of them.

**Comment by Kazzc** [comment]
There are MANY of them on station, I am honestly nervous about changing so many of them. I have a strong feeling it's better to fix the code of them rather than to change them in the map. I will do some testing on how they work and maybe it's better learning how they function rather than changing them in to normal pipes.

**Comment by Shadow-Quill** [comment]
To confirm, is it the pressure regulators or the automatic shutoff valves that are blocking air flow?

**Comment by ExabyteDiscord** [comment]
Most likely been fixed, when testing by venting medical rooms they pressurized as normal once the air alarm was turned back on.
