### ISSUE TITLE
overhaul of bluescreen APC's

### ISSUE THREAD

**Issue by JesusChristItsJasonBourne** [CHOMPStation2/CHOMPStation2#283]
#### Brief overview of the feature
Bluescreen APC's don't have any impact on our server currently as there's no reason for non-engineers to access an APC without self antagging, and events are so rare that actual antags don't really ever encounter or use them, additionally this lacks any compelling reason for engineers to have to hunt down and fix broken APC's

#### What you want to happen
as an APC breaks, it's condition gets worse over time by adding additional affects after time marks, such as spiking in power consumption, and randomly burning out lights as well as causing flickering lights, and eventually shutting off or the APC itself breaking.
 
#### Anything else you may wish to add:
this might have the (very intentional) affect of desensitizing people to shadekin phases, allowing them to catch people off guard when people expect a broken APC to be the cause of a set of flickering/burnt lights.

**Comment by Darlantanis** [comment]
Personally not a fan of this. Engineering is full of nuisance events, I don't see the point to force engineers to go hunting down trivial problems every shift by making them dangerous. The potential of engine failure interrupting scenes alone is enough to push players away from engineering, why modify a nearly guaranteed random event to force another required chore onto engineers each round?

I'll also note players hacking APC's is fairly common but as the bluescreen requires an emag those are rarely caused by players. But on that note it seems unwise to give more power to antags to fuck with engineering given how ubiquitous APC's are.

**Comment by JesusChristItsJasonBourne** [comment]
as you seem to have a habit of taking the entirety of my suggestion as to how to design/deliver it instead of informing me on the specifics you'd prefer or hate, I will note yet again, that not all of this is something I see as required, and that a random broken APC could just have light flickering and light burnouts.

I do however see your point with how few players play engineering because of how engineering is full of nuisance events, but I wish to point out that many events engineering has either range from completely catastrophic to nobody cares and often never anything inbetween, such as the infamous meteor events, which either cause nothing and never happen, or obliterate the station affecting the entire crew and taking hours to repair, perhaps a symptom of the fact that engineering amongst all it's events has nothing to do, until one of few particular events gives them 10x the amount of work as any of the other events

**Comment by JesusChristItsJasonBourne** [comment]
closing request due to lack of interest
