### ISSUE TITLE
Fault in ID authenticator not breaking the authenticator.

### ISSUE THREAD

**Issue by YellowCloak** [CHOMPStation2/CHOMPStation2#309]
#### Brief description of the issue
I check a bluescreened APC and even though it says there is a fault in the ID authenticator I still can't alter anything on the APC, as if it is still locked.

#### What you expected to happen
I expected to be able to turn power on and off to all connected devices from the APC, despite not being an engineer or command.

#### What actually happened
Literally nothing. I couldn't do anything on the APC. It was all still locked.

#### Steps to reproduce
- (Step 1)Find a bluescreened APC, that has a fault with the ID authenticator.
- (Step 2)Look at the pop-up screen after using an empty hand on it.
- (Step 3)Realize you can do nothing on the screen.
- (Step 4)Realize you can't swipe an ID card to even fix it, not even engineering.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Shadow-Quill** [comment]
Something happened where the APC got emmaged, but the cover somehow didn't get unlocked.

The easiest way to fix this (assuming that it could be fixed in the easiest way) would be to bash the panel in with a fire extinguisher or something similar.

Alternative ways would include explosions, a nuclear device, an admin, or the supermatter, after being devoured by a gravitational singularity.

**Comment by ExabyteDiscord** [comment]
This has since been fixed.
