### ISSUE TITLE
Remaining KHI references need commented out/renamed

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#31]
Title

**Comment by Razgriz1032** [comment]
Turns out it's just fluff description for some uniforms.

https://github.com/CHOMPStation2/CHOMPStation2/blob/00495d37721a426de7a6b10b8169f56f7327b4f1/code/modules/client/preference_setup/loadout/loadout_uniform_vr.dm

https://github.com/CHOMPStation2/CHOMPStation2/blob/00495d37721a426de7a6b10b8169f56f7327b4f1/code/modules/vore/fluffstuff/custom_clothes_vr.dm
