### ISSUE TITLE
Shuttle announcements are spammy

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#36]
I've received several complaints that the planet-station shuttle announcements flood the chat. As the shuttle announcements themselves are useful, a compromise would be preferred over outright axing them. Some suggestions thusfar:

1. Tie shuttle times/locations to status displays a bit like the cargo shuttle.
2. Make a specific newscaster channel for shuttle announcements.
3. Replace the shuttles with a different travel method, e.g. a teleporter or less versatile shuttles like those from Northern Star.

**Comment by Dinnel** [comment]
We do have a teleporter but that thing has a turret guarding it and it seems more like for emergencies. Also having a bluespace bag on you or something similar messes with it and teleports you randomly though usually into space. Newscaster seems to be a better choice since you can view it when you want to rather than hearing it on the radio every ding dang time.
