### ISSUE TITLE
Plethora of issues related to using_map.get_map_levels (maybe) making programs function on only one z-level

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#491]
Basically a lot of "check x over multiple z levels" programs now only function on the z-level said program (i.e. the computer using said program) is located in. From my testing so far I believe this is related to using_map.get_map_levels(). From my testing so far this includes:
-Crew monitor 
-Atmosphere alarms
-Power monitor
-Network cards (modular computer wifi)
-Alarm handler
-Space z-level transferring at the edge
I have not tested everything which calls using_map.get_map_levels but suspect the list of broken programs is significantly longer.

This causes #470

**Comment by Razgriz1032** [comment]
Things work OK on Polaris. I think this PR is related. 
https://github.com/PolarisSS13/Polaris/commit/91402f4f504d7db68898ef53222b86e3466a2a42

I am going through various files and comparing them to Polaris and doing process of elimination. I need to check more myself, but at the very least I can say that it is not:
~/maps/~map_system/maps.dm


A major difference we have between Polaris and us is that we split our station map into 3 separate .dmm's instead of keeping them all together as one .dmm with three z-levels. We to smush all three into one file and test it.
