### ISSUE TITLE
Security is missing .45's and rubber bullets

### ISSUE THREAD

**Issue by Draycu** [CHOMPStation2/CHOMPStation2#52]
.45 pistols and the nonlethal ballistics rounds are not currently available within security's vending machine.

I expected to find a ballistics option for use as security, and the only option seems to be available in the armory with higher access above regular security officers required.

Steps to reproduce
- Check the Sec Vend
- Find lacking ballistic weaponry option
- Realize solar grubs' EM pulse can ruin your day
 
Should hopefully be a matter of a quick mapping correction!  The items just need to be available in the vending machine for officer's to get access to in emergencies!

**Comment by Razgriz1032** [comment]
Not sure what you mean by access above regular security officers. I just tested it and walked in and opened glass door to the .45's.
https://i.gyazo.com/226c7ce1b5ea9daba608b035188d52fe.png

We'll take the suggestion for sec vending machine under consideration as this is low priority since there _IS_ access to .45's.

**Comment by Draycu** [comment]
Oh!  I honestly didn't know there was access there, thank you!  I'll close this, the vending machine request is definitely a low priority!
