### ISSUE TITLE
[UI] 

### ISSUE THREAD

**Issue by Pixydidnothingwrong** [CHOMPStation2/CHOMPStation2#5249]
![image](https://user-images.githubusercontent.com/103634148/201426223-a0928f81-85a9-4a58-a56e-6f4f64d2eff5.png)

Is the chem synthesizer UI suppose to do this when you have more than 7 to 8 medications on that list to choose for synthesizing, because this had just happen to me just now and i got no clue what's even going on with it at the moment.

**Comment by ItsSelis** [comment]
This issue might have been fixed with another update as I am unable to replicate this (being able to have >10 medications saved):
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/12716288/f2d8c2c8-0506-4e88-bfef-6eefd78d026c)

General Hint: You can use <kbd>F5</kbd> to reload the tgui window, sometimes it might fix a thing!
