### ISSUE TITLE
Set access requirement for airlock buttons to no access requirements.

### ISSUE THREAD

**Issue by MisterGrimm** [CHOMPStation2/CHOMPStation2#55]
#### Brief description
Title explains it. Have all airlock buttons that open airlocks on internal and external side have no access requirements, so to save individuals in a emergency.

#### What you expected to happen
- Get accidentally spaced somehow or someway, or someone else gets accidentally spaced.
- Person/You uses the external airlock button to quickly open the door, before setting it to let you/them inside.
- Save your/another person's skin from the cold agonizing death of space.

#### What actually happens
- Get accidently spaced, or someone else gets spaced.
- Go to airlock in a attempt to save yourself/someone.
- Try to open the airlock with the external button.
- Access Denied.

#### Steps to reproduce
- Go to any airlock system with buttons.
- Push the internal or external button.
- Watch as some jobs are unable to open the airlocks, and die because of it.

**Comment by Razgriz1032** [comment]
This was standard on airlocks on the old server. Some jobs have access to some airlocks as well as specific area airlocks. This is for security reasons.

**Comment by Dinnel** [comment]
It would be nice but this also can allow people to places unintended for them to be at. While an emergency button would help in exchange for alerting the entire department at whoever is coming in to save people in case of tele-errors it might be just easier to just make sure your backed up... also don't have any bluespace equipment on you when you teleport especially the bluespace backpacks. Maintenance to space should definitely be all access however!

**Comment by Kazzc** [comment]
I think it should be good to have free access to airlocks cause of the nature of them being an airlock.
I think it needs more indepth planning and thinking... unsure if they are just locked cause maints are supposed to be locked to begin with or... is something else. Will think of this before I try to tackle it.

**Comment by Kazzc** [comment]
So I have some issues about this, I can see the uses and caveats on giving all access.

Pro's: 
-More access for antags
-More access for players to explore
-More access to rescue players

Con's:
-Reckless, ignorant or griefers can easily vent maints and the station
-More access for antags

Can't think of much but the level of griefing one can cause with free access to external airlocks can be very glaring.

**Comment by YellowCloak** [comment]
If someone got spaced for some reason, then there is a breach nearby that is still open for them to have flown out of. As such, the breached area and all areas around it are on lockdown. In this case, you will now have to go out of your way to reach an airlock, stopping along the way to grab a suit and put it on, making you even slower, and still open the airlock, navigate to where they are somehow, grab them and drag them back to the airlock or into the breach, still having to possibly throw things to navigate, and then go through at least 1 set of doors, be they airlock or shuttered doors by the breach, to reach habitable areas, still inside the very heavy suit.
If you manage all of this without the spaced individual dying, then either you are very lucky or I am drastically overstating how hard it is to do so in a surprise situation.
My own assumption is that, even if we let airlocks be all-access, the number of factors that have to be perfect for someone to leave through them, grab a person, and return are quite substantial.
I could see giving Out-to-In airlock direction all access, as that would require the person already in space to do such, having made it there on their own in an attempt to save their hide, but allowing anyone to operate them at any time is just a hazard, with the projected positives just not being feasible.

**Comment by MisterGrimm** [comment]
When I originally made this issue the thought was having maintenance airlocks be set to all access, as maintenance itself is already all access. I can easily see the reasoning of department airlocks not being all access, and the thought of griefers causing problems. Although, most maintenance areas with airlocks are usually fairly closed in areas that don't cause any significant amount of potential griefing, compared to something like arrivals.

And on the subject of antags, a airlock they can't access is not going to stop them. They will find a way in if they want in. Be it smashing their way in, emagging, or just having access through illicit means.

**Comment by Admiralkosmov** [comment]
Personally I think this would be a good change. It's a bit annoying when someone accidentally gets locked in and the ONLY ones who can help are engies and heads. Sure, we will get vented more often, but that at least is super easy to fix even from a portable laptop/tablet if needed

The only thing I would like it to have, _PLEASE_ for the sake of our safety make it so that you need to have any STATION access on your ID. None of that 'hey, I'm random space man from god-knows-where and this is jackass' bullshit

**Comment by Kazzc** [comment]
*Fixing atmos in maints is annoying as there are no scrubbers or atmos vents in them, so re-pressurizing vents mean manual work by getting air tanks. And some maints can be very large and wide that will take multiple tanks of air to re-pressurized properly.

*Giving it all-access instead of no access will be a better option yes, I will consider that as a way to access the station, that one needs to have 'AT LEAST' Visitor access to access external air-locks

*Cause of the nature that maints is "all access" making external air-locks be "all access" makes sense.

*Sure, if we do have antags example 'Traitors' will more easily use external airlocks a lot easier, then again... one can get tools to easily hack and use them. If we use "all access" proc's on external airlock, anybody that does not have a station ID will provided one layer of protection against any antags that don't have ID's.

With this points being said... I feel comfortable opting in to giving external airlocks "All access" procs. So one will need to have an ID on hand or on the ID-slot to access External Airlocks. I will get on working on it then.
