### ISSUE TITLE
[GENERAL]  bugs with the Vacuum hose

### ISSUE THREAD

**Issue by zeskorion** [CHOMPStation2/CHOMPStation2#6188]
#### Brief description of the bug
a few bugs with the new janitorial vacuum

1. there is no proximity check.  if the vacuum is linked to a vorebelly, and someone else has it, it still goes to that vorebelly
2. the vacuum can pick up mobs too big for the player to pick up. this is okay for vorny reasons, but is a bit kuch for janitorial purposes
3. the vacuum can put items into a trash bag larger than the bag could hold
4. the vacuum can put more objects into a trash bag (or, at least, a bluespace trash bag) than could be put into it naturally 

#### Steps to reproduce
1. have a player link a vacuum to their belly, then walk off with it

#### Anything else you may wish to add:
I also wish to note the vacuum is excessively powerful for normal janitors. it would be nice to have it run on limited power, for it to have a do_after to clean dusty floors, or simply for it to need to be back-mounted, instead of fitting in a backpack

**Comment by Verkister** [comment]
The first one certainly is an oversight I should fix.
The second one I kinda just didn't consider limiting due to the said vorny reasons, but a size difference check would be a good thing to add.
3's kind of intentional as it would've made the trash bag option completely unusable beyond power level 3 and i just kinda didn't want to gimp it that hard in comparison to the other modes. I did kinda consider adding a new more flexible type of bag for the vac but got lazy.
I feel like 4 probably had to do with a massive pile being sucked at once because that mode currently lacks a capacity check between every item sucked at once, but would be an easy fix to add to my currently open pr.

Yeah seen it definitely op ingame especially with how liberally some folks have been using it recently so a little balance patch would be in order. A separate backpack thing would be a pretty good solution for the problem 3 issues i mentioned. Would just have to make it not usable as a regular backpack due to op storage space. Most likely not even have accessible inventory and taking something out would require dumping the entire contents. This however would require dividing the whole thing into 3-4 separate items/versions and that might take a bit extra time and effort

**Comment by Verkister** [comment]
1 and 4 fixed in https://github.com/CHOMPStation2/CHOMPStation2/pull/6187. Rest will come in a bigger pr later.

**Comment by zeskorion** [comment]
also: does the vacuum check if an item can be trash-ate?
