### ISSUE TITLE
[GENERAL] Solar Storm Genetic Modification Even When Suited

### ISSUE THREAD

**Issue by ZVB334** [CHOMPStation2/CHOMPStation2#6686]
#### Brief description of the bug
When wearing a rad-proof EVA rig, solar storm events will still trigger genetic modifications to you when out of the safe areas. I am unsure if this is an oversight or intended behavior, however.

#### What you expected to happen
Not to be negatively affected by the solar storm.

#### What actually happened
While not irradiated, still received genetic damage.

#### Steps to reproduce
- Wear EVA rig, unsure if issue happens with rad suit.
- Have solar storm happen.
- Gain magic abilities.

**Comment by FoxglovePurpur** [comment]
Adding onto this by saying the same is true for any rad proof.
When the radiation storm event triggers it simply runs a check for who's in the radiation, but doesn't check if you're ableto be affected by it.
Radiation suits, EVA gear, being a promethean, etc-- all do not change the check.

I'd consider this an oversight due to things being added or changed, but the event never being updated alongside it.
