### ISSUE TITLE
[MAPPING] MAP Image Generation fails for Plains and Wilderness

### ISSUE THREAD

**Issue by Kashargul** [CHOMPStation2/CHOMPStation2#8151]
#### Brief description of the bug
Neither Plains nor Wilderness have their maps properly generated, the images are either empty or partial

#### What you expected to happen
The map images to be created properly

#### What actually happened
See above

_____________________________________

=> Z-Level Sorting issue

**Comment by Drulikar** [comment]
Of note, lonehome.dmm was removed from plains.dm because the map was missing most of its data (it had prefabs, but not a single placed tile) https://github.com/CHOMPStation2/CHOMPStation2/pull/8142/files#diff-fa51862f3cf0efd5afc3c30f6a260e3746192ba8a10797aea7ed051e4b4d302aL160-L165

So that would have caused an issue when rendering the map out. I don't know about wilderness though.
