### ISSUE TITLE
[BREAKING] Topical Medications

### ISSUE THREAD

**Issue by Ellirien** [CHOMPStation2/CHOMPStation2#8977]
#### Steps to reproduce
- Using the chemical distiller, produce one lot of bicaridaze (30u foaming agent + 60u bicaridine @390K = 60u bicaridaze).
- Using the chemical processor, produce one 5u bicaridaze patch.
- Apply patch to the patient.
- Patient immediately begins taking toxin damage. Health analyzer will indicate that the patient has 5u of bicaridaze in their bloodstream rather than in their dermis.

#### This issue essentially breaks all patch-based medications, as all medications of the -aze group are toxic when injected. I have tested this with bicaridaze, dermalaze, inaprovalaze, and spacomycaze. All result in toxin damage and do not appear to apply the effects listed in the wiki.

**Comment by tacoguy7765093** [comment]
Blame #8559

**Comment by Missile597** [comment]
This was "added" deliberately by upstream. I did ask that we don't merge is as it breaks all the topical chems but here we are.
https://github.com/CHOMPStation2/CHOMPStation2/pull/8559
All the topical chems need to be thrown at people now because someone decided patches need to work like worse needles to make them useful(?)
